services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.0
    container_name: kubelight-etcd-server
    command:
      - /usr/local/bin/etcd
      - --name=s1
      - --data-dir=/etcd-data
      - --listen-client-urls=http://0.0.0.0:2379
      - --advertise-client-urls=http://etcd:2379
      - --listen-peer-urls=http://0.0.0.0:2380
      - --initial-advertise-peer-urls=http://etcd:2380
      - --initial-cluster=s1=http://etcd:2380
      - --initial-cluster-state=new
    networks:
      - kubelight-net

  manager-api:
    build: ./manager-api
    container_name: manager-api
    ports:
      - "9220:9220"
    environment:
      - ETCD_ENDPOINTS=http://etcd:2379
    depends_on:
      - etcd
    networks:
      - kubelight-net

  kubelet-agent:
    build: ./kubelet-agent
    container_name: kubelet-agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    user: root
    environment:
      - ETCD_ENDPOINTS=http://etcd:2379
    depends_on:
      - etcd
    networks:
      - kubelight-net

networks:
  kubelight-net:
    driver: bridge