### Deploy Nginx
POST {{api_endpoint}}/api/put
Accept: application/json
Content-Type: application/json

{
  "key": "/registry/containers/web-server",
  "value": {
    "name": "web-server",
    "image": "nginx:latest",
    "hostPort": 8081,
    "containerPort": 80
  }
}

### Deploy Redis
POST {{api_endpoint}}/api/put
Accept: application/json
Content-Type: application/json

{
  "key": "/registry/containers/cache-db",
  "value": {
    "name": "cache-db",
    "image": "redis:alpine",
    "hostPort": 6379,
    "containerPort": 6379
  }
}

### Deploy WhoAmI
POST {{api_endpoint}}/api/put
Accept: application/json
Content-Type: application/json

{
  "key": "/registry/containers/whoami",
  "value": {
    "name": "whoami",
    "image": "traefik/whoami",
    "hostPort": 8082,
    "containerPort": 80
  }
}

### GET docker manifests
GET {{api_endpoint}}/api/get?key=/registry/containers/web-server
###
GET {{api_endpoint}}/api/get?key=/registry/containers/cache-db
###
GET {{api_endpoint}}/api/get?key=/registry/containers/whoami


### GET desired spec and current state
GET {{api_endpoint}}/api/containers


### DELETE docker manifests
GET {{api_endpoint}}/api/delete?key=/registry/containers/web-server
###
GET {{api_endpoint}}/api/delete?key=/registry/containers/cache-db
###
GET {{api_endpoint}}/api/delete?key=/registry/containers/whoami