@node = node-1

### Deploy Nginx
POST {{api_endpoint}}/api/put
Accept: application/json
Content-Type: application/json

{
  "value": {
    "name": "web-server",
    "image": "nginx:latest",
    "hostPort": 8081,
    "containerPort": 80
  }
}

### Deploy Nginx 2
POST {{api_endpoint}}/api/put
Accept: application/json
Content-Type: application/json

{
  "value": {
    "name": "web-server2",
    "image": "nginx:latest",
    "hostPort": 8083,
    "containerPort": 80
  }
}

### Deploy Redis
POST {{api_endpoint}}/api/put
Accept: application/json
Content-Type: application/json

{
  "value": {
    "name": "cache-db",
    "image": "redis:alpine",
    "hostPort": 6379,
    "containerPort": 6379
  }
}

### Deploy WhoAmI
POST {{api_endpoint}}/api/put
Accept: application/json
Content-Type: application/json

{
  "value": {
    "name": "whoami",
    "image": "traefik/whoami:latest-amd64",
    "hostPort": 8082,
    "containerPort": 80
  }
}

### GET docker manifests
GET {{api_endpoint}}/api/get?key=/registry/containers/specs/{{node}}/web-server
###
GET {{api_endpoint}}/api/get?key=/registry/containers/specs/{{node}}/cache-db
###
GET {{api_endpoint}}/api/get?key=/registry/containers/specs/{{node}}/whoami


### GET desired spec and current state
GET {{api_endpoint}}/api/containers

### GET containers for nodes
GET {{api_endpoint}}/api/node/containers

### GET the node/heartbeat info
GET {{api_endpoint}}/api/nodes


### DELETE docker manifests
GET {{api_endpoint}}/api/delete?key=/registry/containers/specs/{{node}}/web-server
###
GET {{api_endpoint}}/api/delete?key=/registry/containers/specs/{{node}}/cache-db
###
GET {{api_endpoint}}/api/delete?key=/registry/containers/specs/{{node}}/whoami