server:
  port: 9220
spring:
  application:
   name: sb-etcd

app:
  etcd:
    endpoints: ${ETCD_ENDPOINTS:http://localhost:2379}
    container-prefix: "/registry/containers/specs/"
    container-status-prefix: "/registry/containers/status/"
    node-status-prefix: "/registry/nodes/status/"
    timeout-seconds: 5