server:
  port: 9220
spring:
  application:
   name: sb-etcd

app:
  etcd:
    endpoints: ${ETCD_ENDPOINTS:http://localhost:2379}
    container-prefix: "/registry/containers/"
    status-prefix: "/registry/status/nodes/"
    timeout-seconds: 5