server:
  port:9033
spring:
  application:
    name: sb-mini-kubelet

app:
  node-name: ${NODE_NAME:default-node}
  etcd:
    endpoints: ${ETCD_ENDPOINTS:http://localhost:2379}
    container-prefix: "/registry/containers/specs/"
    container-status-prefix: "/registry/containers/status/"
    node-status-prefix: "/registry/nodes/status/"
    timeout-seconds: 5
    lease-ttl-seconds: 30

